services:
  minio:
    image: quay.io/minio/minio
    networks:
      airflow:
        ipv4_address: 192.168.1.100  # IP fixo para o MinIO
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${PWD}/include/minio:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file: .env

  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8501:8501
      - 8502:8502
    networks:
      - airflow

  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  postgres:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - airflow

  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
      - airflow
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "!@#Dt!@#2025"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: always

networks:
  airflow:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Sub-rede para IPs fixos

volumes:
  sqlserver_data: